import Head from 'next/head'
import styled from 'styled-components'

//components
import Header from '../components/Header';

export default function Home() {
  const MainStyle = styled.main`
    width: 100%;
    height: 100vh;
    background: #0E1420;
  `;

  return (
    <>
      <div>
        <Head>
          <title>Elisabeth Ngo | Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <MainStyle>
          <Header />
        </MainStyle>
        
      </div>
    </>
  )
}
